---
experiment:
  name: Bengali
dataset:
  data_dir: BengaliWords/BengaliWords_CroppedVersion_Folds
  dataset: BengaliWords
  splitname: Fold0_use
  open_world: true
  pretrained_weights: pretrained_model/phosc/epochs.pt
  augmented: false
  use_image_embedder: true
model_params:
  model: compcos
  dropout: true
  norm: true
  nlayers: 2    # Default: 2
  relu: false
  fc_emb: 768,1024,1200
  emb_dim: 512
  # emb_dim: 1395
  emb_init: clip
  image_extractor: resnet18
  train_only: false
  static_inp: false
training:
  # batch_size: 128
  # test_batch_size: 64
  batch_size: 1       # For testing
  test_batch_size: 1  # For testing
  load:
  lr: 5.0e-05       # Default: 5.0e-05
  lrg: 1.0e-03      # Default: 1.0e-03
  wd: 5.0e-05       # Default 5.0e-05
  margin: 0.4
  cosine_scale: 20  # Default 20
  max_epochs: 300
  norm_family: imagenet
  save_every: 10
  test_set: val
  topk: 1
  # workers: 8
  workers: 0  # So the dataloaders work, shared refrence to cuda problems
  update_features: false  # temp, should be `false`
  freeze_features: false
  epoch_max_margin: 15
  cpu_eval: false # Temp
phoscnet: 
  model_name: ResNet18Phosc
  phos_size: 195
  phoc_size: 1200
  phos_layers: 1
  phoc_layers: 1
  dropout: 0.5
  image_resize_x: 1170
  image_resize_y: 414
  language_name: Bengali
  phosc_version: ben
